meta:
  engine: 4.1.0 # Min Ergogen version for KiCad 8 footprints
  name: Whiplaesh
  version: 0.1
  author: ykz89

units:
  # Proxy Spacing Variables
  kx: u
  ky: u
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # MX switch hole
  sx: kx - 5
  sy: ky - 5

  # Physical measures
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

points:
  zones:
    matrix:
      # Fix placement on KiCad sheet.
      anchor:
        shift: [100, -100]
      columns:
        pinky:
          key:
            splay: 15
          rows.top.skip: true
        ring:
          key:
            splay: -10
            stagger: 0.4u
            spread: 1.1u
        middle:
          key:
            stagger: 0.5u
        index:
          key:
            stagger: -0.25u
        inner:
          key:
            stagger: -0.25u
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_inner_top
        shift: [0.25u, -1.5u]
      columns:
        left:
          key:
            splay: -15
        right:
      rows:
        cluster:
          shift: [0, -2u]
  rotate: -5
  mirror: &mirror
      ref: matrix_inner_top
      distance: 5u
outlines:
  keys:
    - what: rectangle
      where: true
      size: [sx, sy]
  board_left:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # Top
        - ref: matrix_inner_top
          shift: [1.45px,0.5py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_home
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_right_cluster
          shift: [0.77px,-0.5py]
        - ref: thumbs_right_cluster
          shift: [0.77px,0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # Top
        - ref: mirror_matrix_inner_top
          shift: [1.45px,0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_home
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_right_cluster
          shift: [0.77px,-0.5py]
        - ref: mirror_thumbs_right_cluster
          shift: [0.77px,0.5py]
  combo_left:
    - name: board_left
    - operation: subtract
      name: keys
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys
pcbs:
  Whiplaesh:
    template: kicad8
    outlines:
      left:
        outline: board_left
      right:
        outline: board_right
    footprints:
      glp_hotswap:
        what: fingerpunch/ks27-choc-v1-mx-soldered-and-hotswap
        where: /^(matrix_|thumbs_|mirror_matrix_|mirror_thumbs_).*/
        params:
          designator: SW
          side: B
          include_switch_hole: true
          include_traces: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^(matrix_|thumbs_|mirror_matrix_|mirror_thumbs_).*/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -10]
      mcu_l:
        what: ceoloide/mcu_nice_nano
        params:
          designator: MCU1
          side: "F"
          reverse_mount: true
          show_silk_labels_on_both_sides: false
        where:
          ref: matrix_inner_top
          shift: [1.1u,-0.265u]
          rotate: 0
      mcu_r:
        what: ceoloide/mcu_nice_nano
        params:
          designator: MCU2
          side: "F"
          reverse_mount: true
          show_silk_labels_on_both_sides: false
        where:
          ref: mirror_matrix_inner_top
          shift: [1.1u,-0.265u]
          rotate: 0
      vik_l:
        what: fingerpunch/vik-keyboard-connector-horizontal
        where:
          ref: matrix_inner_bottom
          shift: [1.5u,-0.5u]
          rotate: 90
        params:
          designator: VIK_OUT1
      vik_r:
        what: fingerpunch/vik-keyboard-connector-horizontal
        where:
          ref: mirror_matrix_inner_bottom
          shift: [1.5u,-0.5u]
          rotate: 90
        params:
          designator: VIK_OUT2
      nice_view_l:
        what: ceoloide/display_nice_view
        where:
          ref: matrix_inner_top
          shift: [1.1u,-0.4u]
        params:
          designator: DISP1
      nice_view_r:
        what: ceoloide/display_nice_view
        where:
          ref: mirror_matrix_inner_top
          shift: [1.1u,-0.4u]
        params:
          designator: DISP2
      jst_l:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_inner_bottom
          shift: [1.25u,0.25u]
          rotate: -90
        params:
          designator: JST1
          side: "B"
      jst_r:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: mirror_matrix_inner_bottom
          shift: [1.25u,0.25u]
          rotate: -90
        params:
          designator: JST2
          side: "B"
      reset_button_l:
        what: ceoloide/reset_switch_tht_top 
        where:
          ref: matrix_inner_top
          shift: [1.65u,-1.75u]
          rotate: 90
        params:
          designator: RST1
      reset_button_r:
        what: ceoloide/reset_switch_tht_top
        where:
          ref: mirror_matrix_inner_top
          shift: [1.65u,-1.75u]
          rotate: 90
        params:
          designator: RST2
      power_switch_l:
        what: ceoloide/power_switch_smd_side
        where:
          ref: thumbs_right_cluster
          shift: [0.86u,0]
          rotate: 0
        params:
          designator: PWR1
          side: "F"
      power_switch_r:
        what: ceoloide/power_switch_smd_side
        where:
          ref: mirror_thumbs_right_cluster
          shift: [0.86u,0]
          rotate: 0
        params:
          designator: PWR2
          side: "F"
      mounting_hole_top_left_l:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: matrix_ring_top
          shift: [-0.7u,0]
      mounting_hole_top_right_l:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: matrix_inner_top
          shift: [-0.25u,0.6u]
      mounting_hole_bottom_right_l:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: matrix_index_bottom
          shift: [-0.25,-1.75u]
      mounting_hole_bottom_left_l:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: matrix_ring_bottom
          shift: [-0.25u,-1.25u]
      front_text_l: &text
        what: ceoloide/utility_text
        where: &textWhere
            ref: matrix_inner_top
            shift: [1.1u, -0.25u]
            rotate: 90
        params: &textParams
            text: Whiplaesh
            thickness: 0.2
            width: 3
            height: 3
      mounting_hole_top_left_r:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: mirror_matrix_ring_top
          shift: [-0.7u,0]
      mounting_hole_top_right_r:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: mirror_matrix_inner_top
          shift: [-0.25u,0.6u]
      mounting_hole_bottom_right_r:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: mirror_matrix_index_bottom
          shift: [-0.25,-1.75u]
      mounting_hole_bottom_left_r:
        what: ceoloide/mounting_hole_plated
        where: 
          ref: mirror_matrix_ring_bottom
          shift: [-0.25u,-1.25u]
      front_text_r: &text
        what: ceoloide/utility_text
        where: &textWhere
            ref: mirror_matrix_inner_top
            shift: [1.1u, -0.25u]
            rotate: 90
        params: &textParams
            text: Whiplaesh
            thickness: 0.2
            width: 3
            height: 3


        

      
