units:
  # Proxy Spacing Variables
  kx: u
  ky: u
  # Padding Variables
  px: kx + 4
  py: ky + 4

points:
  zones:
    matrix:
      # Fix placement on KiCad sheet.
      anchor:
        shift: [100, -100]
      columns:
        pinky:
          key.splay: 15
          rows.top.skip: true
        ring:
          key:
            splay: -10
            stagger: 0.4u
            spread: 1.1u
        middle:
          key:
            stagger: 0.5u
        index:
          key:
            stagger: -0.25u
        inner:
          key:
            stagger: -0.25u
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_inner_top
        shift: [0, -1.5u]
      columns:
        left:
          key:
            splay: -15
        right:
      rows:
        cluster:
          shift: [0, -2u]
  rotate: -20
  mirror: &mirror
      ref: matrix_inner_top
      distance: 5u
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # Top
        - ref: matrix_inner_top
          shift: [1.45px,0.5py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_home
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_right_cluster
          shift: [0.5px,-0.5py]
        - ref: thumbs_right_cluster
          shift: [1px,0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # Top
        - ref: mirror_matrix_inner_top
          shift: [1.45px,0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_home
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_right_cluster
          shift: [0.5px,-0.5py]
        - ref: mirror_thumbs_right_cluster
          shift: [1px,0.5py]
  combo_left:
    - name: board_left
    - operation: subtract
      name: keys
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      glp_hotswap:
        what: ceoloide/switch_gateron_ks27_ks33
        where: /^(matrix_|thumbs_).*/
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^matrix_.*/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -10]
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          side: "F"
          reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [1.1u,-0.265u]
          rotate: 0
      nice_view:
        what: ceoloide/display_nice_view
        where:
          ref: matrix_inner_top
          shift: [1.1u,-0.4u]
        params:
          MOSI: MOSI,
          SCK: SCK,
          VCC: VCC,
          GND: GND,
          CS: CS,
      jst_ph:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_inner_top
          shift: [1.1u,-2.5u]
          rotate: 180
        params:
          side: "B"
          BAT_P: BAT_P
          BAT_N: GND
      reset_button:
        what: ceoloide/reset_switch_tht_top 
        where:
          ref: matrix_inner_top
          shift: [1.65u,-1.75u]   
          rotate: 90
        params:
          from: GND
          to: RST
      power_switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_inner_top
          shift: [1.68u,-2.5u]
        params:
          side: "B"
          from: BAT_P
          to: RAW
      front_text: &text
        what: ceoloide/utility_text
        where: &textWhere
            ref: matrix_middle_bottom
            shift: [0, -2u]
            rotate: -10
        params: &textParams
            text: Whiplash
            thickness: 0.4
            width: 2
            height: 2
      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        where: &textWhere
            ref: matrix_middle_bottom
            shift: [-0.6u, -1.9u]
            rotate: -10
        

      
